language: julia
julia:
- 1.0
os:
- linux
- osx
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("BeaData")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
env:
  global:
  - secure: YCsVUpYndhxUofTuffDDguO995P85gnqid644Q9sUGhAb27uGJS2zf16XxGovymu+UJukzJ+iZ97v0DTb8o+7uILGXWgK5bR8MBuJmsefVenx8swaeLNo3Fi0NAmqFYMpvADq52arqaFt0EfayTuTxSn5AwUbqvhRUlnfukoA8cVfpAJE5lSiT220K/HOu+JJ61o6CuGQRiBgtb9AekTBpFaUjOqyGfNEi7SX/4FBfsDcB5/PwmkNDCaAreMizJFFJkzuaKKl1L69OiatZ9pogrvKgvB+sZDL1Nzo1TyEsZRGsCEUC9uMjB0kMEsbbVFtKNvh9hOoMLm9vanU6mbzJPxyUGsdwR8xWQlvHTldADWAkhSE/oJYzBMM8depbR5mwKbtS7yX23tkMIw8xdOnGrYirShJh7zgGbqOPKtg7/UzGrPngrJ99WzMTbR532ZlScZe0QAP863QZh/coM9ixbDLb/in/Wl+cLFJ86xuB0r+LntVT5Nw88hMod+KNzxSRnR+7dMJHHKAKYSTgL2YNjBEjVF53jKvVjF4tOkzwWRVqJk2sXfM0VIaIOVsdgjEz2tNIl7gBoIItrbHLlFbboeTPz9e7B0lEwERpDgrU4XpIsc8T3pblmre/jN+UKr4DEaA27PGYOKJOAp7mdbEmTMMOMKZRaGxV0Xf0v/0qg=
  - secure: igLh1sUggc9dDdIjqxrvD1iihwh6rcbTIH+6XMne3bAIW74S0ku6KOl1LnUDg3+BHmD+Nk97coXTfMCsfGFiENZdHSD4BZ/csTHOfjteG4jvvDwEX9AbegeIEDeOzvp446vupcLexc/1n2mgWABYnDCf3r7/LqhBnHauYF6Jx4PyQl2H1fOWVjvjkrQKiqcmCiAXC7E2GkEmzJc1NstKw+/W53uSTdrV4q2Wy/SNqB52GxzNbkk2JlXlTw9kHkru2lxe94s7xALiV1S1ezd74SPIkSdJB5LIoRZk+6nW+BNd33OUZKgudaEWuOYeiOPeGGaRPFO7bhTV54RL//ATWpynvi5mn24EGr47AfxkW81CR51t4ivUrJCVPkdjiI0VXfhEw4zZiQWbiGnqd14+mTzAuozRkS0uP6NoD19AoQYABrhMpK4aVHdWp0yvevlKlhWIn2kx7z2R3i6+IQDaBR05r1yRzkGdWHMXS2+noWqcMTUMwvUCjyV3AYXIalyQsTF0aL07MUFJQw0ZAT4rUdp1rUyvnqFQMJipVN9SHO42HW85PM4iunQw0pV5iEhs9rnDmxni60SpH9O7QzWRrFYTMD8lHUA42MXnEBlD49MKsG5kltcX17wlwUw82FnlCAPQ3ezdut81rYvTxRC22evsOXBdrjuXFg8MUpUTkWM=

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
